name: dztrainfay
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.10.1
  google_maps_flutter_platform_interface: ^2.4.0
  geolocator: ^13.0.2
  dio: ^5.4.0
  intl: ^0.18.0
  http: ^1.3.0
  permission_handler: ^11.0.0
  flutter_polyline_points: ^2.0.0

  # Firebase dependencies
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.4

  # Other dependencies
  font_awesome_flutter: ^10.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/image-backround.png
    - assets/images/image-backround1.png
    - assets/images/image-backround2.png
