name: githubapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.4
  font_awesome_flutter: ^10.8.0
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.0.2
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/train.gif
    - assets/images/background-.png
    - assets/images/background2.jpg
    - assets/images/localisation.jpg
    - assets/images/DZ_TRAIN.png
    - assets/images/image-backround1.png
    - assets/images/image-backround2.png
    - assets/images/image-backround.png
    - assets/images/logo3.png

flutter_native_splash:
  color: "#F5F5DC"
  image: assets/images/logo3.png
  android: true
  ios: true
  android_12:
    image: assets/images/logo3.png
    icon_background_color: "#F5F5DC"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo3.png"
  adaptive_icon_background: "#000000"
  min_sdk_android: 23
